### ISSUE TITLE
HTTP Trigger with Encrypted Body doesn't trigger executions

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-fs#104]
### Issue description

```yaml
id: send_alert_price
namespace: dev

tasks:
  - id: slack
    type: io.kestra.core.tasks.log.Log
    message: "The price is now below the threshold: {{ json(trigger.body).products[0].price }}"

triggers:
  - id: http
    type: io.kestra.plugin.fs.http.Trigger
    uri: https://dummyjson.com/products/search?q=macbook-pro
    responseCondition: "{{ json(response.body).products[0].price < 1800 }}"
    interval: PT1S
    encryptBody: true
    stopAfter:
      - SUCCESS
```

This doesn't create any executions

When you remove the `encryptBody`, it works

**Comment by anna-geller** [comment]
PEBKAC

the right version is to use encryptBody:

```yaml
id: send_alert_when_price_drops48
namespace: dev

tasks:
  - id: slack
    type: io.kestra.core.tasks.log.Log
    message: "The price is now below the threshold: {{ json(trigger.encryptBody).products[0].price }}"

triggers:
  - id: http48
    type: io.kestra.plugin.fs.http.Trigger
    uri: https://dummyjson.com/products/search?q=macbook-pro
    responseCondition: "{{ json(response.body).products[0].price < 1800 }}"
    interval: PT1S
    encryptBody: true
    stopAfter:
      - SUCCESS
```
