### ISSUE TITLE
Standard regex fails with white space

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-fs#109]
### Actual Behaviour

The following regex `.*test Test_nbs_issuers_.+.csv` should match on this string "test Test_nbs_issuers_YYYYMMDD.csv" but the white space seems to cause an issue using the `regEx` property.

```
id: regex
namespace: dev

tasks:
  - id: fs
    host: localhost
    port: 21
    username: foo
    password: pass
    type: io.kestra.plugin.fs.ftp.List
    from: "/folder"
    regExp: .*test Test_nbs_issuers_.+.csv
 ```

### Environment Information

- Kestra Version:
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):
