### ISSUE TITLE
http.Request POST response body returns request body instead

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/plugin-fs#121]
### Expected Behavior

When you make a POST request with `io.kestra.plugin.fs.http.Request` using a JSON body, you can access the response body through `{{ outputs.task_id.body }}`.

### Actual Behaviour

When you make a POST request and access the output, the `body` is the same as the property `body` used to make the request.

### Steps To Reproduce

Run the following flow:
```yaml
id: http_request_example
namespace: example
description: Make a HTTP Request and Handle the Output

inputs:
  - id: payload
    type: JSON
    defaults: |
      [{"name": "Will", "job": "Developer Advocate"}]

tasks:
  - id: send_data
    type: io.kestra.plugin.fs.http.Request
    uri: https://reqres.in/api/users
    method: POST
    contentType: application/json
    body: "{{ inputs.payload }}"

  - id: print_status
    type: io.kestra.core.tasks.log.Log
    message: "{{ outputs.send_data.body }}"
```

The output will look like this (the same as the request body):
![image](https://github.com/kestra-io/plugin-fs/assets/34094921/100a1039-5d7f-4881-b720-66b52c39e75f)

[Documentation for the API](https://reqres.in/)

Postman is able to get a response body that matches the documentation. 
![Screenshot 2024-04-19 at 15 38 02](https://github.com/kestra-io/plugin-fs/assets/34094921/ae7f0b5d-d5d0-4923-a886-cbe9777db0b1)
![Screenshot 2024-04-19 at 15 38 16](https://github.com/kestra-io/plugin-fs/assets/34094921/ba4ddf44-7191-47fe-b9c3-d56bee674b4e)

### Environment Information

- Kestra Version: 0.16.1
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

Example 1
```yaml
id: http_request_example
namespace: example
description: Make a HTTP Request and Handle the Output

inputs:
  - id: payload
    type: JSON
    defaults: |
      [{"name": "Will", "job": "Developer Advocate"}]

tasks:
  - id: send_data
    type: io.kestra.plugin.fs.http.Request
    uri: https://reqres.in/api/users
    method: POST
    contentType: application/json
    body: "{{ inputs.payload }}"

  - id: print_status
    type: io.kestra.core.tasks.log.Log
    message: "{{ outputs.send_data.body }}"
```

Example 2
```yaml
id: rest_api_with_inputs
namespace: dev

labels:
  env: prod
  country: US

tasks:
  - id: extract
    type: io.kestra.plugin.fs.http.Request
    uri: https://dummyjson.com/products
    method: GET

  - id: load
    type: io.kestra.plugin.fs.http.Request
    uri: https://reqres.in/api/products
    method: POST
    contentType: application/json
    body: "{{outputs.extract.body}}"
```
