### ISSUE TITLE
SSH Command plugin does not work when loading private key from a secret

### ISSUE THREAD

**Issue by xionous** [kestra-io/plugin-fs#129]
### Expected Behavior

Be able to establish a SSH connection when loading a private key from a secret

### Actual Behaviour

Unable to establish a SSH connection when loading a private key from a secret

### Steps To Reproduce

1. launch kestra with docker
2. attach private key with env variable that is base64 encoded
3. run task with secret

I have validated that the environment variable is correct by decoding the key in the docker console and using ssh directly in the docker console to make a connection. The key also works when added to the flow directly in plain text, it only does not work when loaded from a secret.

### Environment Information

- Kestra Version: 0.16.6
- Plugin version: 0.16.0
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

### Example flow

Flow that works
```
id: test
namespace: test
description: test

inputs:
  - id: host
    type: STRING

tasks:
  - id: install-docker-on-host
    type: io.kestra.plugin.fs.ssh.Command
    authMethod: PUBLIC_KEY
    commands:
      - pwd
    host: "{{ inputs.host }}"
    privateKey: |-
        -----BEGIN OPENSSH PRIVATE KEY-----
        ...redacted...
        -----END OPENSSH PRIVATE KEY-----
    username: root
```

Flow that doesn't
```
id: test
namespace: test
description: test
inputs:
  - id: host
    type: STRING

tasks:
  - id: install-docker-on-host
    type: io.kestra.plugin.fs.ssh.Command
    authMethod: PUBLIC_KEY
    commands:
      - pwd
    host: "{{ inputs.host }}"
    privateKey: "{{ secret('ID_KEY') }}"
    username: root
```
