### ISSUE TITLE
Allow options to chunk logging of ssh outputs

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/plugin-fs#141]
### Feature description

I am using an ssh command to run a JAR file which runs some batch logic in a remote server. 
The output of the command is very verbose, with lots of data. 
Currently, the plugin outputs one log record per line of the shell output, which results in up to 30,000 database records being saved in Postgres per execution. I want to be able to save these logs, but not in such an inefficient way that every curly brace or a square bracket in a json output is saved as a separate log. 
A workaround is to first save the log into a variable and echo the output, like this : 

```
tasks:
  - id: start_batch
    type: io.kestra.plugin.fs.ssh.Command
    commands:
      - cd /app/instances/cm-bat
      - output=$(./springBatch.sh <batch jar with print output>)
      - exit_code=$?
      - echo $output
      - exit $exit_code
    host: "{{ render(namespace.batch.dev.host) }}"  
    password: "{{ render(namespace.batch.dev.password) }}"
    username: "{{ render(namespace.batch.dev.username) }}"
```

But then the log is unformatted, and looks like this in the Kestra output : 

![image](https://github.com/user-attachments/assets/0bdd7547-d145-4268-9cfb-6b95f2cb6914)

I wish there was an option in the task to be able to chunk the log output while keeping all the formatting.

**Comment by anna-geller** [comment]
Hi John, I struggle to understand the issue. Do you want to capture outputs from a Shell task without generating a log? 

Can you share a small example that allows us to reproduce the issue you see?

keep in mind that you can set a custom `logLevel` e.g. `logLevel: WARN` to avoid storing such INFO logs as shown above

**Comment by johnkm516** [comment]
> Hi John, I struggle to understand the issue. Do you want to capture outputs from a Shell task without generating a log?
> 
> Can you share a small example that allows us to reproduce the issue you see?
> 
> keep in mind that you can set a custom `logLevel` e.g. `logLevel: WARN` to avoid storing such INFO logs as shown above

Hi Anna, 

Sorry, I don't think I explained myself very well. 
I want to generate a log, but I want to be able to chunk the log output such that each log record contains a number of lines of the output (set by an option in the ssh activity) rather than Kestra generating a log record for each line of the output. Here is an example of what I'm talking about : 

```
id: batch-cm
namespace: erp.cm

tasks:
  - id: start_batch
    type: io.kestra.plugin.fs.ssh.Command
    commands:
      - cd /app/instances/cm-bat
      - ./springBatch.sh messageMakeJob

    host: "{{ render(namespace.batch.host) }}"  
    password: "{{ render(namespace.batch.password) }}"
    username: "{{ render(namespace.batch.username) }}"

  - id: Log
    type: io.kestra.plugin.core.log.Log
    message: '{{ outputs.start_batch.vars.batchlog }}'
concurrency:
  limit: 1
  behavior: CANCEL
```

./springBatch.sh executes a JAR file which outputs random JSON outputs, about 20,000 lines of output. When Kestra executes the above flow, the ssh command takes about 2 minutes 14 seconds to execute, because it's creating a log record line by line, like this : 

<img width="775" alt="image" src="https://github.com/user-attachments/assets/962e26a1-0c9a-4d32-a54e-5f8af09d919b">

If I modify the shell script to first store the output in a variable and output it like below : 

```
id: batch-cm
namespace: erp.cm

tasks:
  - id: start_batch
    type: io.kestra.plugin.fs.ssh.Command
    commands:
      - cd /app/instances/cm-bat
      - output=$(./springBatch.sh messageMakeJob)
      - escaped_json=$(echo "$output" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/\$/\\$/g')
      - echo '::{"outputs":{"batchlog":"'$escaped_json'"}}::'

    host: "{{ render(namespace.batch.host) }}"  
    password: "{{ render(namespace.batch.password) }}"
    username: "{{ render(namespace.batch.username) }}"

  - id: Log
    type: io.kestra.plugin.core.log.Log
    message: '{{ outputs.start_batch.vars.batchlog }}'
concurrency:
  limit: 1
  behavior: CANCEL
```

The activity takes significantly less time to execute, completing in around 6 seconds, but the output is not formatted : 

<img width="798" alt="image" src="https://github.com/user-attachments/assets/766aefae-5ced-4ba3-aabf-05f2e45db8da">

For performance and storage reasons, creating a new log record in the DB for each line of the shell script output is an issue. Each log record in Kestra comes with metadata such as timestamp, level, thread, etc., all of which is replicated 20,000 times, one for each line of output in my above flow. In cases of outputting a prettified JSON, Kestra would be storing metadata for a single line containing just a curly brace.

I would like the option to be able to output the log in batches, rather than line by line. For example, if I set the option to 1000, the worker would first read and load 1000 lines of the shell output into its memory before saving the output as a log record in the DB.
