### ISSUE TITLE
"Move" operation will treat moveDirectory as a file if missing a trailing /

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/plugin-fs#160]
### Describe the issue

If sftp task is configured to move file(s), if the moveDirectory is missing a trailing `/` it will treat the directory as a file

```
triggers:
  - id: sftp_downloads
    type: io.kestra.plugin.fs.sftp.Trigger
    host: hostname
    username: user
    keyfile: "{{secret('ssh_key')}}"
    from: /home/user/data
    regExp: ".*.txt"
    action: MOVE
    moveDirectory: /home/user/data/sftp_loc
    rootDir: false
```

on the SFTP host set up the following
- `mkdir -p /home/user/data/sftp_loc`
- `echo testing >> /home/user/data/my_file.txt`

Allow trigger to execute. Observe that `/home/user/data/sftp_loc` is now a file containing the word "testing

Expectation is that with or without the trailing `/` "moveDirectory" should be treated as a directory

### Environment

- Kestra Version: latest
