### ISSUE TITLE
SMB trigger does not escape symbols & outputs passwords plain text

### ISSUE THREAD

**Issue by qui458** [kestra-io/plugin-fs#163]
### Describe the issue

hi!
currently I am testing `io.kestra.plugin.fs.smb.Trigger` and it seems that extra secure passwords do not work with, - it throws Illegal character in authority at index error and outputs a *plain text exposed password* to logs as well (see in screenshot). seems like the plugin does not escape all the symbols, but only a few (1st in screenshot is why the error comes up, 2nd is being escaped, ie. converted to hex).
in my flow config I am using KV store for password, so it should act as a string normally.
am I perhaps setting something wrong, or is there a minor issue with the trigger plugin itself?

thanks!

flow:
```
id: orders_to_coloplast
namespace: aph.demo

triggers:
  - id: rs_order
    type: io.kestra.plugin.fs.smb.Trigger
    host: host_name
    port: "445"
    username: "{{ kv('smb_user') }}"
    password: "{{ kv('smb_passwd') }}"
    from: /Stora_Test/RS/Data/PurchaseOrders/Effectuated Orders/Coloplast/Temp
    regExp: ".*.XML"
    interval: "PT60S"
    action: MOVE
    moveDirectory: /Stora_Test/RS/Data/PurchaseOrders/Effectuated Orders/Coloplast/Sent

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀 {{ trigger.outputFiles }}
```

issuing screenshot:
![image (3)](https://github.com/user-attachments/assets/273cf9ff-a9b1-4d21-b3ef-081248983902)

### Environment

- Kestra Version: develop
