### ISSUE TITLE
Different behavior when passing ARRAY in payload

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-fs#168]
### Describe the issue

Is it normal to have a different behavior between the following syntax?

```yaml
    formData:
      parameters:
        an_array:
          - value1
          - value2
```
```yaml
    formData:
      parameters:
        an_array: "{{ inputs.my_array }}" # inputs.my_array is of type ARRAY
```

Here is my flow for example, and I have two different API response depending of the choosen syntax

```
id: user_research_categorization_feedback
namespace: kestra

inputs:
  - id: user_message
    type: STRING


tasks:
  - id: http
    type: io.kestra.plugin.core.http.Request
    uri: https://api-inference.huggingface.co/models/facebook/bart-large-mnli
    method: POST
    contentType: application/json
    headers:
      Authorization: "Bearer {{ secret('HF_API_TOKEN') }}"
    formData:
      inputs: "{{ inputs.user_message }}"
      parameters:
        candidate_labels:
          - refund
          - new_feature
          - legal

  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "{{ json(outputs.http.body).labels[0] }}" 
```

Here is the output - well formatted/expected : `{"sequence":"refund","labels":["refund","legal","new_feature"],"scores":[0.8690019845962524,0.07823403179645538,0.05276406183838844]}` 

when using: 
```yaml
    formData:
      inputs: "{{ inputs.user_message }}"
      parameters:
        candidate_labels: "['refund', 'new_feature', 'legal']"
```

the output is different and mixed : `{"sequence":"I need this new feature in product","labels":["\"new_feature\"","\"legal\"]","[\"refund\""],"scores":[0.836469829082489,0.11843764036893845,0.04509248584508896]}`

### Environment

- Kestra Version: develop
