### ISSUE TITLE
Add a file detection trigger for local files the same way as we support that for SFTP

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-fs#180]
### Feature description

Equivalent plugin to https://kestra.io/plugins/plugin-fs/sftp/io.kestra.plugin.fs.sftp.trigger but for local files

Especially useful when combined with a `workerGroup.key`

Add a warning that this won't work in a distributed setup e.g. deployed on Kubernetes

**Comment by anna-geller** [comment]
We should include all plugins to make that local file system subplugin behave the same way as e.g. SFTP (Copy, Move, Delete, List, Upload, Download + Trigger)

**Comment by Malaydewangan09** [comment]
@anna-geller to confirm
We need all the tasks similar to those in other subplugins, in our `Local file system` subplugin, in addition to the `trigger` right?
And can I please get an example reproducer for one of the tasks - maybe `Upload` ?

This is what I've come upto for a basic version after the implementation
LMKYT

```
id: fs_local_upload
namespace: company.team

inputs:
  - id: file
    type: FILE

tasks:
  - id: upload
    type: io.kestra.plugin.fs.local.Upload
    from: "{{ inputs.file }}"
    to: "test/test.pdf"
    basePath: "/Users/dev/desktop/kestra-output"
                  
```
