### ISSUE TITLE
[HTTP] Retry policy based on HTTP code (body ?)

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/plugin-fs#58]
### Feature description

It would be great to be able to define the retry policy of HTTP tasks based on the HTTP Response code or body.
For eg. we should be able to have an infinite retry on 5XX errors but not on 4XX
Maybe something like that :
```
retry:
  valueOf: {{outputs.myHttpRequest.code}}
  policies:
    '5\d*':
      type: constant
      interval: PT30S
    '400':
      type: none
  default:
    type: constant
    interval: PT30S
    maxAttempt: 3
```
